# -*- conf -*-

term=xterm-256color

# make the text a bit fatter, works well with semi-light font
gamma-correct-blending=yes
font=CaskaydiaMono Nerd Font:SemiLight:size=12.8

[key-bindings]
fullscreen=Alt+Return

# vim: ft=dosini
