# -*- conf -*-
# template: /etc/xdg/foot/foot.ini

term=xterm-256color

font=Cascadia Mono NF:weight=60:size=12.8
letter-spacing=-0.5

initial-window-size-chars=120x30
initial-window-mode=fullscreen

[key-bindings]
fullscreen=Alt+Return

# vim: ft=dosini cms=#\ %s
